version: 1
disable_existing_loggers: false

formatters:  
  standard:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

loggers:
  ibm_watsonx_orchestrate:
    level: DEBUG
    handlers: [console]